# NumPy Essentials for ML

<a target="_blank" href="https://colab.research.google.com/github/imamitjain/notebooks/blob/main/01-python-for-ml/01_numpy_essentials.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Objective:** Master NumPy array operations that form the foundation of all ML computation — creation, indexing, broadcasting, and linear algebra.

**Prerequisites:** Basic Python knowledge

In [ ]:
import sys

if "google.colab" in sys.modules:
    %pip install -q numpy


In [ ]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.4


## 1. Array Creation

In [ ]:
# From lists
a = np.array([1, 2, 3, 4, 5])
print(f"1D array: {a}, shape: {a.shape}, dtype: {a.dtype}")

# 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D array shape: {matrix.shape}")

# Common constructors
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
identity = np.eye(3)
rng = np.random.default_rng(42)
random_arr = rng.standard_normal((3, 3))

print(f"Zeros:\n{zeros}")
print(f"Identity:\n{identity}")
print(f"Random:\n{random_arr}")

1D array: [1 2 3 4 5], shape: (5,), dtype: int64
2D array shape: (2, 3)
Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Identity:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random:
[[ 0.30471708 -1.03998411  0.7504512 ]
 [ 0.94056472 -1.95103519 -1.30217951]
 [ 0.1278404  -0.31624259 -0.01680116]]


## 2. Indexing and Slicing

In [ ]:
arr = np.arange(20).reshape(4, 5)
print(f"Array:\n{arr}\n")

# Basic slicing
print(f"Row 1: {arr[1]}")
print(f"Column 2: {arr[:, 2]}")
print(f"Submatrix (2x2 top-left):\n{arr[:2, :2]}")

# Boolean indexing
mask = arr > 10
print(f"\nElements > 10: {arr[mask]}")

# Fancy indexing
rows = [0, 2, 3]
print(f"Rows 0, 2, 3:\n{arr[rows]}")

Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Row 1: [5 6 7 8 9]
Column 2: [ 2  7 12 17]
Submatrix (2x2 top-left):
[[0 1]
 [5 6]]

Elements > 10: [11 12 13 14 15 16 17 18 19]
Rows 0, 2, 3:
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## 3. Broadcasting

Broadcasting lets NumPy operate on arrays of different shapes without copying data.

In [ ]:
# Scalar broadcast
a = np.array([[1, 2, 3], [4, 5, 6]])
print(f"a * 10:\n{a * 10}\n")

# Row vector broadcast
row = np.array([100, 200, 300])
print(f"a + row:\n{a + row}\n")

# Column vector broadcast
col = np.array([[10], [20]])
print(f"a + col:\n{a + col}")

a * 10:
[[10 20 30]
 [40 50 60]]

a + row:
[[101 202 303]
 [104 205 306]]

a + col:
[[11 12 13]
 [24 25 26]]


## 4. Linear Algebra (ML Essentials)

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
print(f"A @ B:\n{A @ B}\n")

# Transpose
print(f"A.T:\n{A.T}\n")

# Determinant and inverse
print(f"det(A): {np.linalg.det(A):.1f}")
print(f"inv(A):\n{np.linalg.inv(A)}\n")

# Eigenvalues (used in PCA, spectral methods)
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Eigenvalues: {eigenvalues}")

A @ B:
[[19 22]
 [43 50]]

A.T:
[[1 3]
 [2 4]]

det(A): -2.0
inv(A):
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues: [-0.37228132  5.37228132]


## 5. Vectorized Operations (Why NumPy is Fast)

In [ ]:
import time

size = 1_000_000
py_list = list(range(size))
np_arr = np.arange(size)

# Python loop
start = time.perf_counter()
result_py = [x ** 2 for x in py_list]
time_py = time.perf_counter() - start

# NumPy vectorized
start = time.perf_counter()
result_np = np_arr ** 2
time_np = time.perf_counter() - start

print(f"Python loop: {time_py:.4f}s")
print(f"NumPy:       {time_np:.4f}s")
print(f"Speedup:     {time_py / time_np:.0f}x")

Python loop: 0.0321s
NumPy:       0.0014s
Speedup:     23x


## Try It Yourself

1. Create a 5x5 matrix of random integers between 1 and 100. Compute its mean, std, and the sum of each row.
2. Given two vectors `a = [1, 2, 3]` and `b = [4, 5, 6]`, compute the dot product, cross product, and cosine similarity.
3. Create a 1000-element array of random values from a normal distribution. Find what percentage of values fall within 1 standard deviation of the mean.

In [ ]:
# Your code here
